import { getThemedColor } from '@worldresources/wri-design-systems'
import type { Config } from 'tailwindcss'

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'neutral-100': getThemedColor('neutral', 100),
        'neutral-200': getThemedColor('neutral', 200),
        'neutral-300': getThemedColor('neutral', 300),
        'neutral-400': getThemedColor('neutral', 400),
        'neutral-500': getThemedColor('neutral', 500),
        'neutral-600': getThemedColor('neutral', 600),
        'neutral-700': getThemedColor('neutral', 700),
        'neutral-800': getThemedColor('neutral', 800),
        'neutral-900': getThemedColor('neutral', 900),
        'primary-100': getThemedColor('primary', 100),
        'primary-200': getThemedColor('primary', 200),
        'primary-300': getThemedColor('primary', 300),
        'primary-400': getThemedColor('primary', 400),
        'primary-500': getThemedColor('primary', 500),
        'primary-600': getThemedColor('primary', 600),
        'primary-700': getThemedColor('primary', 700),
        'primary-800': getThemedColor('primary', 800),
        'primary-900': getThemedColor('primary', 900),
        'secondary-100': getThemedColor('secondary', 100),
        'secondary-200': getThemedColor('secondary', 200),
        'secondary-300': getThemedColor('secondary', 300),
        'secondary-400': getThemedColor('secondary', 400),
        'secondary-500': getThemedColor('secondary', 500),
        'secondary-600': getThemedColor('secondary', 600),
        'secondary-700': getThemedColor('secondary', 700),
        'secondary-800': getThemedColor('secondary', 800),
        'secondary-900': getThemedColor('secondary', 900),
        'success-100': getThemedColor('success', 100),
        'success-200': getThemedColor('success', 200),
        'success-300': getThemedColor('success', 300),
        'success-400': getThemedColor('success', 400),
        'success-500': getThemedColor('success', 500),
        'success-600': getThemedColor('success', 600),
        'success-700': getThemedColor('success', 700),
        'success-800': getThemedColor('success', 800),
        'success-900': getThemedColor('success', 900),
        'warning-100': getThemedColor('warning', 100),
        'warning-200': getThemedColor('warning', 200),
        'warning-300': getThemedColor('warning', 300),
        'warning-400': getThemedColor('warning', 400),
        'warning-500': getThemedColor('warning', 500),
        'warning-600': getThemedColor('warning', 600),
        'warning-700': getThemedColor('warning', 700),
        'warning-800': getThemedColor('warning', 800),
        'warning-900': getThemedColor('warning', 900),
        'error-100': getThemedColor('error', 100),
        'error-200': getThemedColor('error', 200),
        'error-300': getThemedColor('error', 300),
        'error-400': getThemedColor('error', 400),
        'error-500': getThemedColor('error', 500),
        'error-600': getThemedColor('error', 600),
        'error-700': getThemedColor('error', 700),
        'error-800': getThemedColor('error', 800),
        'error-900': getThemedColor('error', 900),
        'accessible-text-on-primary-mids': getThemedColor('accessible', 'text-on-primary-mids'),
        'accessible-text-on-secondary-mids': getThemedColor('accessible', 'text-on-secondary-mids'),
        'accessible-controls-on-neutral-lights': getThemedColor('accessible', 'controls-on-neutral-lights'),
        'accessible-controls-on-neutral-darks': getThemedColor('accessible', 'controls-on-neutral-darks'),
      },
    },
  },
  plugins: [],
} satisfies Config
